BooksCatalogue/Controllers/AttributeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entity;
using System.Threading.Tasks;
using System.Data.Entity;
using BooksCatalogue.Models;
using System.Net;
using System.IO;
using System.Xml;

namespace BooksCatalogue.Controllers
{
    public class AttributeController : Controller
    {
        public  static MyAttribute attribute;
        public static Error error;

        private BooksCatalogueEntities1 context = new BooksCatalogueEntities1();
        // GET: Attribute
        public  ActionResult Index()
        {
            return View( Meneger.Meneger.GetAttributes());
        }
        public ActionResult Create()
        {
            ViewBag.TypeID= new SelectList(context.AttributesTypes, "ID", "AttributeType");
            return View();
        }

        [HttpPost]
         [ValidateAntiForgeryToken]
        public  ActionResult Create(string name, int TypeID, int? maxCharackterCount, int? mincharkcterCount)
        {
            if(name == null || maxCharackterCount == null || mincharkcterCount == null)
            {
                Error errortemp = new Error();
                errortemp.Name = "emptyFild";
                errortemp.Messag = "inpute error or Type error. do not fill in all fields? Or the wrong types of fields filled in/MaxCharackterCount and MincharkcterCount must be int type /";
                error = errortemp;
                return RedirectToAction("Error");
            }
          
            if (maxCharackterCount < mincharkcterCount)
            {
                Error errortemp = new Error();
                errortemp.Name = "CreateAttribute";
                errortemp.Messag = "inpute error. maxCharackterCount(Max) < mincharkcterCount(Min)";
                error = errortemp;
                return RedirectToAction("Error");
            }
            if (ModelState.IsValid)
            {
                Meneger.Meneger.CreateAttribute(name, TypeID, maxCharackterCount, mincharkcterCount);
                return RedirectToAction("Index");
            }
            ViewBag.TypeID = new SelectList(context.AttributesTypes, "ID", "AttributeType", attribute.TypeID);
            return View(attribute);

        }
        public  ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var attribute = Meneger.Meneger.Find(id);
            attribute.AttributeTextXmlName = Helper.Helper.XmlTextDeSerialization(attribute.AttributName);
            ViewBag.MinCharackterCount = attribute.AttributeTextXmlName.MaxCharacterCount;
            if (attribute == null)
            {
                return HttpNotFound();
            }
            ViewBag.Name = attribute.AttributeTextXmlName.Name;
            ViewBag.MaxCharacterCount = attribute.AttributeTextXmlName.MaxCharacterCount;
            ViewBag.MinCharacterCount = attribute.AttributeTextXmlName.MinCharacterCount;

            ViewBag.TypeID = new SelectList(context.AttributesTypes, "ID", "AttributeType", attribute.TypeID);
            return View(attribute);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MyAttribute attribute, string Name, int TypeID, int? MaxCharacterCount, int? MinCharacterCount)
        {
            if (ModelState.IsValid)
            {
                Meneger.Meneger.EditAttribute(attribute, Name, TypeID, MaxCharacterCount, MinCharacterCount);
                return RedirectToAction("Index");
            }
            ViewBag.TypeID = new SelectList(context.AttributesTypes, "ID", "AttributeType", attribute.TypeID);
            return View(attribute);
        }
        //Get popoxum e attributi arjeq@
        public ActionResult EditAttributeValue(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AttributeXMLTextValueModel attribute = Helper.Helper.XmlTextValueDeSerialization(context.AttributValues.Find(id).AttributValue1);
            if (attribute == null)
            {
                return HttpNotFound();
            }
            return View(attribute);
        }

        [HttpPost]//post popoxum e atributi arjeq@
        public ActionResult EditAttributeValue(string value, int id)
        {
            if (value != null && ModelState.IsValid)
            {
                MyAttribute attrTemp = Meneger.Meneger.Find(attribute.ID);
                attribute = attrTemp;
                Meneger.Meneger.EditAttributeValue(value, id);
            }
            else
            {
                Error error = new Error();
                error.Messag = "do not enter an attribute value";
             //   return Error(error);
            }
              
                return RedirectToAction("AttributeAddTextValue");
            
        }

        // GET: Delete/1 Attribute value 
        public ActionResult DeleteAttributeValue(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AttributeXMLTextValueModel attribute = Helper.Helper.XmlTextValueDeSerialization(context.AttributValues.Find(id).AttributValue1);
            if (attribute == null)
            {
                return HttpNotFound();
            }
            return View(attribute);
        }
        // POST: Delete Attribute Value
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteAttributeValue(int id)// jnjeluc jnjel book attribut tabli hamapatasxan tox@ 
        {
            Meneger.Meneger.DeleteAttributeValue(id);
            return RedirectToAction("AttributeAddTextValue");
        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var attribute = Meneger.Meneger.Find(id);
            attribute.AttributeTextXmlName = Helper.Helper.XmlTextDeSerialization(attribute.AttributName);
            if (attribute == null)
            {
                return HttpNotFound();
            }
            return View(attribute);
        }
        //Get delete Attribut
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                Error error = new Error();
                error.Messag = "Bad request";
               // return Error(error);
            }
            MyAttribute attribute = Meneger.Meneger.Find(id);

            if (attribute == null)
            {
                return HttpNotFound();
            }
            return View(attribute);
        }

        // POST: 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            MyAttribute attribute = Meneger.Meneger.Find(id);
            Meneger.Meneger.Remove(attribute);
            return RedirectToAction("Index");
        }


        public ActionResult AttributeValue()//cucadrum e text tipi atributneri arjeqner@
        {
            List<AttributeXMLTextValueModel> atrValueList = new List<AttributeXMLTextValueModel>();
            foreach (var item in context.AttributValues)
            {
                if (item!= null)
                {
                    AttributeXMLTextValueModel atrValue = new AttributeXMLTextValueModel();
                    atrValue = Helper.Helper.XmlTextValueDeSerialization(item.AttributValue1);
                    atrValue.AttributeValueID = item.ID;
                    atrValueList.Add(atrValue);
                }
            }
            
            
            return PartialView("_AttributeAddTextValue", atrValueList);//cucadrum e text tipi antributneri arjeqner@
        }
        public ActionResult AttributeAddTextValue()//cucadrum e text  tipi atributi avelacman ej@ 
        {   
            return View(attribute);
        }
     
        // GET: Add Attribute Value
        public ActionResult AddAttributeValue(int? id) //cucadrum e hamapatasxan tipi atributi arjeqi avelacman ej@
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            MyAttribute atr= Meneger.Meneger.Find(id);
            attribute = atr;
            if (attribute == null)
            {
                return HttpNotFound();
            }
            ViewBag.AttributeType = context.AttributesTypes.Find(attribute.TypeID).AttributeType;
            if (ViewBag.AttributeType == "text")
                return RedirectToAction("AttributeAddTextValue");
            return View(atr);
        }

        [HttpPost]
         [ValidateAntiForgeryToken]
        public  ActionResult AddAttributeValue(string value)
        {
            if(Meneger.Meneger.ValidationAttributeValue(value, attribute.ID) == false)
            {
                Error errortemp = new Error();
                errortemp.Name = "AttributeValueValidation";
                errortemp.Messag = "error input: Attribute value of the number of symbols in error";
                error = errortemp;
                return RedirectToAction("Error");
            }
            if (value != null && ModelState.IsValid)
            { 
                MyAttribute attrTemp = Meneger.Meneger.Find(attribute.ID);
                attribute = attrTemp;
                Meneger.Meneger.AddAttributeValue( value, attribute.ID);// 

                }
                if(value == null)
                {
                    Error errortemp = new Error();
                    errortemp.Messag = "do not enter an attribute value";
                    error = errortemp; 
                    return RedirectToAction("Error");
                }
            
            return RedirectToAction("AttributeAddTextValue");

BooksCatalogue/Views/Attribute/AttributeAddTextValue.cshtml
@model BooksCatalogue.Models.MyAttribute

@{
    ViewBag.Title = "AttributeAddTextValueView";
}

<head>
    <link href="~/Content/Site.css" rel="stylesheet" />
</head>
@using (Html.BeginForm("AddAttributeValue", "Attribute", FormMethod.Post, new { enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal myHorzontal">
       
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID)

            <div class="form-group">
                @Html.Label("Name", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AttributeTextXmlName.Name, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.AttributeTextXmlName.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Type", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AttributesType.AttributeType, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.TypeID, "", new { @class = "text-danger" })
                </div>
            </div>
        <div class="form-group">
            @Html.Label("Max", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AttributeTextXmlName.MaxCharacterCount, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.AttributeTextXmlName.MaxCharacterCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Min", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AttributeTextXmlName.MinCharacterCount, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.AttributeTextXmlName.MinCharacterCount, "", new { @class = "text-danger" })
            </div>
        </div>
            <div class="form-group">
                @Html.Label("Value", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.Editor("Value", new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AttributValues, "", new { @class = "text-danger" })
                </div>
            </div>

          
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </div>
    </div>

}
<div  id ="attributevalueList" style="display:inline-block; float:right; margin-top: -354px; margin-right: 60px;">
  @{ 
      Html.RenderAction("AttributeValue", "Attribute");
      
  }

 
</div>

BooksCatalogue/Views/Attribute/Create.cshtml
@model BooksCatalogue.Models.MyAttribute

@{
    ViewBag.Title = "Create";
}


@using (Html.BeginForm("Create", "Attribute", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Name:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Editor("name", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AttributName, "", new { @class = "text-danger" })
            </div>
        </div>
        
        
        <div class="form-group">
            @Html.Label("Type:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TypeID", null, htmlAttributes: new { @class = "form-control", @style = "height:40px;" })
                @Html.ValidationMessageFor(model => model.TypeID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Max:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Editor("maxCharackterCount", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AttributName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Min:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Editor("mincharkcterCount", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AttributName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10" id="attributeCreate">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BooksCatalogue/Views/Attribute/Delete.cshtml
@model BooksCatalogue.Models.MyAttribute

@{
    ViewBag.Title = "Delete";
}
<p style="font-size: 20px;">Are you sure you want to delete this?</p>
<div>

    <hr />
    <dl class="dl-horizontal">


      
        <dt>
            @Html.DisplayName("Name")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AttributeTextXmlName.Name)
        </dd>

        <dt>
            @Html.DisplayName("Type")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AttributesType.AttributeType)
        </dd>
        <dt>
            @Html.DisplayName("Max")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AttributeTextXmlName.MaxCharacterCount)
        </dd>

        <dt>
            @Html.DisplayName("Min")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AttributeTextXmlName.MinCharacterCount)
        </dd>
    </dl>


</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color"id="attributedDelete">
        <input type="submit" value="Delete" class="btn btn-default" />
    </div>
}

BooksCatalogue/Views/Attribute/DeleteAttributeValue.cshtml
@model BooksCatalogue.Models.AttributeXMLTextValueModel

@{
    ViewBag.Title = "DeleteAttributeValue";
}


<h3 id="attrValueDeleteH3">Are you sure you want to delete this?</h3>
<div>
    
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Value")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>
        
</dl>

@using(Html.BeginForm("DeleteAttributeValue", "Attribute", FormMethod.Post, new { enctype = "multipart/form-data" }))
       
    {
     @Html.AntiForgeryToken()

        <div class="form-actions no-color" id="AttrValueDeletdelet">
            <input type="submit" value="Delete" class="btn btn-default"/> 
            </div>
            <div class="AttrValueDeletBackToLit">
            @Html.ActionLink("Back to List",  "AttributeAddTextValue")
        </div>
    }
</div>

BooksCatalogue/Views/Attribute/Details.cshtml
@model BooksCatalogue.Models.MyAttribute

@{
    ViewBag.Title = "Details";
}

<div>
    <h4>Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Name")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AttributeTextXmlName.Name)
        </dd>

        <dt>
            @Html.DisplayName("Type")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AttributesType.AttributeType)
        </dd>
        <dt>
            @Html.DisplayName("Max")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AttributeTextXmlName.MaxCharacterCount)
        </dd>
        <dt>
            @Html.DisplayName("Min")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AttributeTextXmlName.MinCharacterCount)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

BooksCatalogue/Views/Attribute/Edit.cshtml
@model BooksCatalogue.Models.MyAttribute

<head>
    <link href="~/Content/Site.css" rel="stylesheet"/>
</head>
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Attribute", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.Label("Name:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Editor("Name",null, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AttributeTextXmlName.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Type:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TypeID", null, htmlAttributes: new { @class = "form-control", @style = "height:40px;" })
                @Html.ValidationMessageFor(model => model.TypeID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Max:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Editor("MaxCharacterCount", null, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AttributeTextXmlName.MaxCharacterCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Min:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Editor("MinCharacterCount", null, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AttributeTextXmlName.MinCharacterCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10" id="AttributeEdit">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div id="AttributeEditBackToList">
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
} 

BooksCatalogue/Views/Attribute/EditAttributeValue.cshtml
@model BooksCatalogue.Models.AttributeXMLTextValueModel
@{
    ViewBag.Title = "EditAttributeValue";
}

<head><link href="~/Content/Site.css" rel="stylesheet" /></head>

@using (Html.BeginForm("EditAttributeValue", "Attribute", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group " style="margin-top">
            @Html.Label("Value:", htmlAttributes: new { @class = "control-label col-md-2", style = "margin-top:70px;" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control", style = "margin-top:70px;margin-left: -117px" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10" id="editAttributeValue">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div id="AttrValueEditBackToList">
    @Html.ActionLink("Back to List", "AttributeAddTextValue")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BooksCatalogue/Views/Attribute/Index.cshtml
@model IEnumerable<BooksCatalogue.Models.MyAttribute>
@{
    ViewBag.Title = "Index";
}
<head>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

</head>
<div class="navbar navbar-inverse"   style="background-color:#FFFCB5; margin-top:60px;margin-bottom:-50px;">
<a href="@Url.Action("Create", "Attribute")" id="grid" class="btn btn-default btn-sm " style="font-size: 17px; height:38px; margin-bottom:-8px;background-color: #D6BBA0;margin-left:4px">
    <span class="glyphicon glyphicon-plus-sign"></span>Attribute
</a>
</div>


<table class="table" id="myTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Name")
            </th>
            <th>
                @Html.DisplayName("Type")
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.AttributeTextXmlName.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AttributesType.AttributeType)
                </td>
               
                <td>
                    <a href="@Url.Action("Details", "Attribute",new { id = item.ID })" id="Table" class="btn btn-default btn-sm"><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="@Url.Action("Edit", "Attribute",new { id = item.ID })" id="Table" class="btn btn-default btn-sm"><i class="glyphicon glyphicon-pencil"></i></a>
                    <a href="@Url.Action("Delete", "Attribute", new { id = item.ID })" id="Table" class="btn btn-default btn-sm"><i class="glyphicon glyphicon-remove"></i></a>
                    <a href="@Url.Action("AddAttributeValue", "Attribute",new { id = item.ID })" id="Table" class="btn btn-default btn-sm" style="background-color:#D6BBA0;">
                        <span class="glyphicon glyphicon-plus-sign"></span>Value
                    </a>
                </td>
            </tr>
        }
    </tbody>

</table>


@section scripts
{
    <script type="text/javascript"></script>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="~/Scripts/Categoria/Categoria.js"></script>
}

BooksCatalogue/Views/Attribute/_AttributeAddTextValue.cshtml
@model IEnumerable<BooksCatalogue.Models.AttributeXMLTextValueModel>
@{
    ViewBag.Title = "Index";
}
<head>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="~/Content/Site.css" rel="stylesheet" />
</head>

<table class="table" id="myTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Value")
            </th>
           
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Value)
                </td>
                <td>
                    <a href="@Url.Action("EditAttributeValue", "Attribute",new { id =item.AttributeValueID})" id="EditAttributValue" class="btn btn-default btn-sm">
                        <span class="glyphicon glyphicon-pencil"> </span>
                    </a> 
                    <a href="@Url.Action("DeleteAttributeValue", "Attribute",new { id =item.AttributeValueID})" id="DeleteAttributValue" class="btn btn-default btn-sm" style="background-color:#D6BBA0;">
                        <span class="glyphicon glyphicon-remove"></span>
                    </a>      
                </td>
            </tr>
        }
    </tbody>

</table>


@section scripts
{
    <script type="text/javascript"></script>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="~/Scripts/Categoria/Categoria.js"></script>
}